### ISSUE TITLE
Revisión del README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-cafetsidi#1]
Hola,

He revisado el README:

- La propuesta de trabajo es poco ambiciosa y poco original. Tenéis que reformularla. Echad un vistazo a las propuestas de otros equipos y a los trabajos del curso pasado.
- Faltan los objetivos.
- Podéis enlazar cada participante a su página web de GitHub.

**Comment by Joshgv25** [comment]
Hemos añadido más información a la descripción del trabajo, esperemos que esté a la altura. También hemos añadido objetivos y puesto las cuentas de GitHub de cada participante
