### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-cafetsidi#2]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by Joshgv25** [comment]
El programa con el menú lo hemos añadido ya. Si hay algún fallo, por favor comuníquenoslo. 
Gracias.

**Comment by lquintanac** [comment]
Buenas, tenéis que cerrar la issue una vez completada.
